Repository uchicago-capp-30320/new-arrivals-chi, pull requests merged in 2024-04, with the labels that each got.

#19 Update issue templates
  .github/ISSUE_TEMPLATE/admin_template.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#17 feat(doc): updating gitignore
  .gitignore
Labels: documentation

#20 Add poetry files with pre-commit library and hooks
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: documentation

#24 Adding license to repo
  LICENSE.md
Labels: documentation

#25 Create README.md
  README.md
Labels: documentation

#23 feat(test): add pytest to poetry env
  .github/ISSUE_TEMPLATE/feature_request.md
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/example_test.py
  tests/readme.md
Labels: documentation, testing

#69 Created the base and updated the home page to extend the base
  new_arrivals_chi/app/templates/base.html
  new_arrivals_chi/app/templates/home.html
Labels: feature

#51 Endpoint Documentation
  docs/architecture.md
  docs/changelog.md
  docs/decisions/architecture.md
  docs/decisions/authentication.md
  docs/decisions/backend_framework.md
  docs/decisions/database.md
  docs/decisions/frontend_framework.md
  docs/decisions/server.md
  docs/endpoints/admin.md
  docs/endpoints/general_info.md
  docs/endpoints/health.md
  docs/endpoints/home.md
  docs/endpoints/index.md
  docs/endpoints/legal.md
  docs/endpoints/organization.md
  docs/index.md
  docs/models/data_model.md
  docs/models/model.md
Labels: admin

#90 pytest-flask core fixtures and home page testing
  poetry.lock
  pyproject.toml
  tests/app_home_test.py
  tests/conftest.py
  tests/example_test.py
  tests/readme.md
Labels: testing

#93 Exclude markdown documents from pre-commit trailing whitespace rule
  .pre-commit-config.yaml
  tests/readme.md
Labels: bug
