Repository uchicago-capp-30320/new-arrivals-chi, pull requests merged in 2024-05, with the labels that each got.

#119 User sign up functionality and injection into database
  new_arrivals_chi/app/__init__.py
  new_arrivals_chi/app/authorize_routes.py
  new_arrivals_chi/app/database.py
  new_arrivals_chi/app/main.py
  new_arrivals_chi/app/templates/signup.html
  new_arrivals_chi/app/utils.py
  new_arrivals_chi/migrations/versions/2024-05-01-2238_65ad78872dbb_change_password_length.py
  poetry.lock
  pyproject.toml
Labels: feature

#120 Login_functionality
  new_arrivals_chi/app/authorize_routes.py
  new_arrivals_chi/app/main.py
  new_arrivals_chi/app/templates/base.html
Labels: feature

#121 Upper buttons render based on authentication status
  new_arrivals_chi/app/templates/base.html
Labels: feature

#122 Implement change password logic, skeleton HTML, and update the DB reference
  new_arrivals_chi/app/authorize_routes.py
  new_arrivals_chi/app/templates/change_password.html
  new_arrivals_chi/app/templates/profile.html
Labels: feature

#158 Implement security fixes recommended by GH
  requirements.txt
Labels: dependencies

#161 (test) SQL Injections to test database security vulnerabilities
  tests/readme.md
  tests/setup_fake_db.py
  tests/sql_injection_test.py
Labels: testing

#168 (feat): build legal flow objects
  docs/endpoints/legal.md
  new_arrivals_chi/app/languages/en.json
  new_arrivals_chi/app/languages/es.json
  new_arrivals_chi/app/main.py
  new_arrivals_chi/app/static/css/legal.css
  new_arrivals_chi/app/static/css/main.css
  new_arrivals_chi/app/static/js/legal_data.js
  new_arrivals_chi/app/static/js/legal_flow.js
  new_arrivals_chi/app/templates/asylum_apply.html
  new_arrivals_chi/app/templates/asylum_info.html
  new_arrivals_chi/app/templates/general.html
  new_arrivals_chi/app/templates/help.html
  new_arrivals_chi/app/templates/legal_flow.html
  new_arrivals_chi/app/templates/parole_apply.html
  new_arrivals_chi/app/templates/parole_info.html
  new_arrivals_chi/app/templates/renters_rights.html
  new_arrivals_chi/app/templates/tps_apply.html
  new_arrivals_chi/app/templates/tps_info.html
  new_arrivals_chi/app/templates/undocumented_resources.html
  new_arrivals_chi/app/templates/vttc_apply.html
  new_arrivals_chi/app/templates/vttc_info.html
  new_arrivals_chi/app/templates/work_rights.html
  tests/legal_routes_test.py
Labels: feature
